# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'The Bubble App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for The Bubble App
  pod 'Starscream', '~> 3.0.2'
end
